modLoader="javafml"
loaderVersion="[34,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"
[[mods]]
modId="elenaihardcore"
version="1.0.0"
displayName="Elenai Hardcore"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/elenai-hardcore"
credits="ElenaiDev"
authors="Elenai"
description='''
Welcome to Elenai Hardcore!
Elenai Hardcore is a stamina mod that focuses on overhauling the vanilla game.
Have a look at the Mod Config for more settings! Navigate to:
.minecraft/config/elenaihardcore-client.toml
.minecraft/config/elenaihardcore-common.toml
Enjoy!

A MASSIVE thanks to my Patrons: SandwichHorror, Brent, DevilDogHons, Ethan McGowen (ArtyArtyArtemis)
'''
[[dependencies.elenaihardcore]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.elenaihardcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elenaihardcore]]
    modId="elenaidodge2"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="NONE"
    side="BOTH"
